In [17]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\win8\anaconda3\lib\site-packages (0.17.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\win8\anaconda3\lib\site-packages (from mlxtend) (0.14.1)
Requirement already satisfied: setuptools in c:\users\win8\anaconda3\lib\site-packages (from mlxtend) (45.2.0.post20200210)
Requirement already satisfied: pandas>=0.24.2 in c:\users\win8\anaconda3\lib\site-packages (from mlxtend) (1.0.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\win8\anaconda3\lib\site-packages (from mlxtend) (1.18.1)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\win8\anaconda3\lib\site-packages (from mlxtend) (0.22.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\win8\anaconda3\lib\site-packages (from mlxtend) (3.1.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\win8\anaconda3\lib\site-packages (from mlxtend) (1.4.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\win8\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\win8\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2019.3)
Requirement already satisfied: cycler>=0.10 in c:\users\win8\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\win8\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\win8\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.6)
Requirement already satisfied: six>=1.5 in c:\users\win8\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.24.2->mlxtend) (1.14.0)

In [2]:
import pandas as pd

In [9]:
df=pd.read_csv("datasets_344_727_GroceryStoreDataSet.csv",names=["products"])

In [10]:
df

                          products
0               MILK,BREAD,BISCUIT
1    BREAD,MILK,BISCUIT,CORNFLAKES
2              BREAD,TEA,BOURNVITA
3             JAM,MAGGI,BREAD,MILK
4                MAGGI,TEA,BISCUIT
5              BREAD,TEA,BOURNVITA
6             MAGGI,TEA,CORNFLAKES
7          MAGGI,BREAD,TEA,BISCUIT
8              JAM,MAGGI,BREAD,TEA
9                       BREAD,MILK
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11  COFFEE,COCK,BISCUIT,CORNFLAKES
12          COFFEE,SUGER,BOURNVITA
13               BREAD,COFFEE,COCK
14             BREAD,SUGER,BISCUIT
15         COFFEE,SUGER,CORNFLAKES
16           BREAD,SUGER,BOURNVITA
17              BREAD,COFFEE,SUGER
18              BREAD,COFFEE,SUGER
19      TEA,MILK,COFFEE,CORNFLAKES

In [11]:
df.columns

Index(['products'], dtype='object')

In [12]:
df.values

array([['MILK,BREAD,BISCUIT'],
       ['BREAD,MILK,BISCUIT,CORNFLAKES'],
       ['BREAD,TEA,BOURNVITA'],
       ['JAM,MAGGI,BREAD,MILK'],
       ['MAGGI,TEA,BISCUIT'],
       ['BREAD,TEA,BOURNVITA'],
       ['MAGGI,TEA,CORNFLAKES'],
       ['MAGGI,BREAD,TEA,BISCUIT'],
       ['JAM,MAGGI,BREAD,TEA'],
       ['BREAD,MILK'],
       ['COFFEE,COCK,BISCUIT,CORNFLAKES'],
       ['COFFEE,COCK,BISCUIT,CORNFLAKES'],
       ['COFFEE,SUGER,BOURNVITA'],
       ['BREAD,COFFEE,COCK'],
       ['BREAD,SUGER,BISCUIT'],
       ['COFFEE,SUGER,CORNFLAKES'],
       ['BREAD,SUGER,BOURNVITA'],
       ['BREAD,COFFEE,SUGER'],
       ['BREAD,COFFEE,SUGER'],
       ['TEA,MILK,COFFEE,CORNFLAKES']], dtype=object)

In [13]:
data=list(df["products"].apply(lambda x:x.split(",")))
data

[['MILK', 'BREAD', 'BISCUIT'],
 ['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['JAM', 'MAGGI', 'BREAD', 'MILK'],
 ['MAGGI', 'TEA', 'BISCUIT'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['MAGGI', 'TEA', 'CORNFLAKES'],
 ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'],
 ['JAM', 'MAGGI', 'BREAD', 'TEA'],
 ['BREAD', 'MILK'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'COCK'],
 ['BREAD', 'SUGER', 'BISCUIT'],
 ['COFFEE', 'SUGER', 'CORNFLAKES'],
 ['BREAD', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]

In [27]:
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [19]:
te = TransactionEncoder()
te_data = te.fit(data).transform(data)
df = pd.DataFrame(te_data,columns=te.columns_)
df

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,True,False,True,False,False,False,False,False,True,False,False
1,True,False,True,False,False,True,False,False,True,False,False
2,False,True,True,False,False,False,False,False,False,False,True
3,False,False,True,False,False,False,True,True,True,False,False
4,True,False,False,False,False,False,False,True,False,False,True
5,False,True,True,False,False,False,False,False,False,False,True
6,False,False,False,False,False,True,False,True,False,False,True
7,True,False,True,False,False,False,False,True,False,False,True
8,False,False,True,False,False,False,True,True,False,False,True
9,False,False,True,False,False,False,False,False,True,False,False
10,True,False,False,True,True,True,False,False,False,False,False
11,True,False,False,True,True,True,False,False,False,False,False
12,False,True,False,False,True,False,False,False,False,True,False
13,False,False,True,True,True,False,False,False,False,False,False
14,True,False,True,False,False,False,False,False,False,True,False
15,False,False,False,False,True,True,False,False,False,True,False
16,False,True,True,False,False,False,False,False,False,True,False
17,False,False,True,False,True,False,False,False,False,True,False
18,False,False,True,False,True,False,False,False,False,True,False
19,False,False,False,False,True,True,False,False,True,False,True

In [20]:
from mlxtend.frequent_patterns import apriori

In [21]:
df1 = apriori(df,min_support=0.1,use_colnames=True)
df1.head()

   support     itemsets
0     0.35    (BISCUIT)
1     0.20  (BOURNVITA)
2     0.65      (BREAD)
3     0.15       (COCK)
4     0.40     (COFFEE)

In [22]:
df1.shape

(46, 2)

In [23]:
df1.sort_values(by = 'support', ascending = False)

    support                             itemsets
2      0.65                              (BREAD)
4      0.40                             (COFFEE)
0      0.35                            (BISCUIT)
10     0.35                                (TEA)
5      0.30                         (CORNFLAKES)
9      0.30                              (SUGER)
7      0.25                              (MAGGI)
8      0.25                               (MILK)
30     0.20                      (COFFEE, SUGER)
34     0.20                         (TEA, MAGGI)
11     0.20                     (BREAD, BISCUIT)
29     0.20                 (COFFEE, CORNFLAKES)
26     0.20                         (BREAD, TEA)
25     0.20                       (BREAD, SUGER)
24     0.20                        (BREAD, MILK)
1      0.20                          (BOURNVITA)
21     0.15                      (BREAD, COFFEE)
27     0.15                       (COFFEE, COCK)
23     0.15                       (BREAD, MAGGI)
3      0.15                               (COCK)
18     0.15                   (BOURNVITA, BREAD)
14     0.15                (BISCUIT, CORNFLAKES)
19     0.10                   (BOURNVITA, SUGER)
44     0.10           (COFFEE, COCK, CORNFLAKES)
43     0.10                  (BREAD, TEA, MAGGI)
42     0.10                  (BREAD, MAGGI, JAM)
41     0.10               (BREAD, SUGER, COFFEE)
40     0.10              (BOURNVITA, TEA, BREAD)
39     0.10                (BISCUIT, TEA, MAGGI)
38     0.10        (COFFEE, BISCUIT, CORNFLAKES)
37     0.10          (BISCUIT, COCK, CORNFLAKES)
36     0.10              (COFFEE, BISCUIT, COCK)
35     0.10               (MILK, BREAD, BISCUIT)
32     0.10                    (TEA, CORNFLAKES)
33     0.10                         (MAGGI, JAM)
20     0.10                     (BOURNVITA, TEA)
31     0.10                   (MILK, CORNFLAKES)
6      0.10                                (JAM)
12     0.10                      (BISCUIT, COCK)
28     0.10                   (COCK, CORNFLAKES)
13     0.10                    (COFFEE, BISCUIT)
15     0.10                     (BISCUIT, MAGGI)
16     0.10                      (MILK, BISCUIT)
17     0.10                       (BISCUIT, TEA)
22     0.10                         (BREAD, JAM)
45     0.10  (COFFEE, BISCUIT, COCK, CORNFLAKES)

In [24]:
df1['length'] = df1['itemsets'].apply(lambda x:len(x))
df1

    support                             itemsets  length
0      0.35                            (BISCUIT)       1
1      0.20                          (BOURNVITA)       1
2      0.65                              (BREAD)       1
3      0.15                               (COCK)       1
4      0.40                             (COFFEE)       1
5      0.30                         (CORNFLAKES)       1
6      0.10                                (JAM)       1
7      0.25                              (MAGGI)       1
8      0.25                               (MILK)       1
9      0.30                              (SUGER)       1
10     0.35                                (TEA)       1
11     0.20                     (BREAD, BISCUIT)       2
12     0.10                      (BISCUIT, COCK)       2
13     0.10                    (COFFEE, BISCUIT)       2
14     0.15                (BISCUIT, CORNFLAKES)       2
15     0.10                     (BISCUIT, MAGGI)       2
16     0.10                      (MILK, BISCUIT)       2
17     0.10                       (BISCUIT, TEA)       2
18     0.15                   (BOURNVITA, BREAD)       2
19     0.10                   (BOURNVITA, SUGER)       2
20     0.10                     (BOURNVITA, TEA)       2
21     0.15                      (BREAD, COFFEE)       2
22     0.10                         (BREAD, JAM)       2
23     0.15                       (BREAD, MAGGI)       2
24     0.20                        (BREAD, MILK)       2
25     0.20                       (BREAD, SUGER)       2
26     0.20                         (BREAD, TEA)       2
27     0.15                       (COFFEE, COCK)       2
28     0.10                   (COCK, CORNFLAKES)       2
29     0.20                 (COFFEE, CORNFLAKES)       2
30     0.20                      (COFFEE, SUGER)       2
31     0.10                   (MILK, CORNFLAKES)       2
32     0.10                    (TEA, CORNFLAKES)       2
33     0.10                         (MAGGI, JAM)       2
34     0.20                         (TEA, MAGGI)       2
35     0.10               (MILK, BREAD, BISCUIT)       3
36     0.10              (COFFEE, BISCUIT, COCK)       3
37     0.10          (BISCUIT, COCK, CORNFLAKES)       3
38     0.10        (COFFEE, BISCUIT, CORNFLAKES)       3
39     0.10                (BISCUIT, TEA, MAGGI)       3
40     0.10              (BOURNVITA, TEA, BREAD)       3
41     0.10               (BREAD, SUGER, COFFEE)       3
42     0.10                  (BREAD, MAGGI, JAM)       3
43     0.10                  (BREAD, TEA, MAGGI)       3
44     0.10           (COFFEE, COCK, CORNFLAKES)       3
45     0.10  (COFFEE, BISCUIT, COCK, CORNFLAKES)       4

In [25]:
df1[(df1['length']==2) & (df1['support']>=0.1)]

    support               itemsets  length
11     0.20       (BREAD, BISCUIT)       2
12     0.10        (BISCUIT, COCK)       2
13     0.10      (COFFEE, BISCUIT)       2
14     0.15  (BISCUIT, CORNFLAKES)       2
15     0.10       (BISCUIT, MAGGI)       2
16     0.10        (MILK, BISCUIT)       2
17     0.10         (BISCUIT, TEA)       2
18     0.15     (BOURNVITA, BREAD)       2
19     0.10     (BOURNVITA, SUGER)       2
20     0.10       (BOURNVITA, TEA)       2
21     0.15        (BREAD, COFFEE)       2
22     0.10           (BREAD, JAM)       2
23     0.15         (BREAD, MAGGI)       2
24     0.20          (BREAD, MILK)       2
25     0.20         (BREAD, SUGER)       2
26     0.20           (BREAD, TEA)       2
27     0.15         (COFFEE, COCK)       2
28     0.10     (COCK, CORNFLAKES)       2
29     0.20   (COFFEE, CORNFLAKES)       2
30     0.20        (COFFEE, SUGER)       2
31     0.10     (MILK, CORNFLAKES)       2
32     0.10      (TEA, CORNFLAKES)       2
33     0.10           (MAGGI, JAM)       2
34     0.20           (TEA, MAGGI)       2

In [28]:
report=association_rules(df1, metric = "confidence", min_threshold = 0.2).sort_values(by='confidence', ascending=False)
report

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
58,"(BISCUIT, COCK)",(CORNFLAKES),0.10,0.30,0.10,1.000000,3.333333,0.0700,inf
104,"(COFFEE, COCK, CORNFLAKES)",(BISCUIT),0.10,0.35,0.10,1.000000,2.857143,0.0650,inf
54,"(BISCUIT, COCK)",(COFFEE),0.10,0.40,0.10,1.000000,2.500000,0.0600,inf
90,(JAM),"(BREAD, MAGGI)",0.10,0.15,0.10,1.000000,6.666667,0.0850,inf
48,"(BISCUIT, MILK)",(BREAD),0.10,0.65,0.10,1.000000,1.538462,0.0350,inf
...,...,...,...,...,...,...,...,...,...
112,(COFFEE),"(BISCUIT, COCK, CORNFLAKES)",0.40,0.10,0.10,0.250000,2.500000,0.0600,1.200
55,(COFFEE),"(BISCUIT, COCK)",0.40,0.10,0.10,0.250000,2.500000,0.0600,1.200
23,(BREAD),(MAGGI),0.65,0.25,0.15,0.230769,0.923077,-0.0125,0.975
20,(BREAD),(COFFEE),0.65,0.40,0.15,0.230769,0.576923,-0.1100,0.780
15,(BREAD),(BOURNVITA),0.65,0.20,0.15,0.230769,1.153846,0.0200,1.040

In [32]:
report.sort_values(by="confidence",ascending=False).head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
58,"(BISCUIT, COCK)",(CORNFLAKES),0.10,0.30,0.10,1.0,3.333333,0.070,inf
22,(JAM),(BREAD),0.10,0.65,0.10,1.0,1.538462,0.035,inf
109,"(BISCUIT, COCK)","(COFFEE, CORNFLAKES)",0.10,0.20,0.10,1.0,5.000000,0.080,inf
76,"(BOURNVITA, TEA)",(BREAD),0.10,0.65,0.10,1.0,1.538462,0.035,inf
106,"(COFFEE, BISCUIT)","(COCK, CORNFLAKES)",0.10,0.10,0.10,1.0,10.000000,0.090,inf
111,"(COCK, CORNFLAKES)","(COFFEE, BISCUIT)",0.10,0.10,0.10,1.0,10.000000,0.090,inf
105,"(BISCUIT, COCK, CORNFLAKES)",(COFFEE),0.10,0.40,0.10,1.0,2.500000,0.060,inf
71,"(BISCUIT, MAGGI)",(TEA),0.10,0.35,0.10,1.0,2.857143,0.065,inf
52,"(COFFEE, BISCUIT)",(COCK),0.10,0.15,0.10,1.0,6.666667,0.085,inf
70,"(BISCUIT, TEA)",(MAGGI),0.10,0.25,0.10,1.0,4.000000,0.075,inf
103,"(COFFEE, BISCUIT, CORNFLAKES)",(COCK),0.10,0.15,0.10,1.0,6.666667,0.085,inf
102,"(COFFEE, BISCUIT, COCK)",(CORNFLAKES),0.10,0.30,0.10,1.0,3.333333,0.070,inf
104,"(COFFEE, COCK, CORNFLAKES)",(BISCUIT),0.10,0.35,0.10,1.0,2.857143,0.065,inf
98,"(COCK, CORNFLAKES)",(COFFEE),0.10,0.40,0.10,1.0,2.500000,0.060,inf
32,(COCK),(COFFEE),0.15,0.40,0.15,1.0,2.500000,0.090,inf
64,"(COFFEE, BISCUIT)",(CORNFLAKES),0.10,0.30,0.10,1.0,3.333333,0.070,inf
87,"(BREAD, JAM)",(MAGGI),0.10,0.25,0.10,1.0,4.000000,0.075,inf
88,"(JAM, MAGGI)",(BREAD),0.10,0.65,0.10,1.0,1.538462,0.035,inf
60,"(COCK, CORNFLAKES)",(BISCUIT),0.10,0.35,0.10,1.0,2.857143,0.065,inf
44,(JAM),(MAGGI),0.10,0.25,0.10,1.0,4.000000,0.075,inf